---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: lfa
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    quotas:
      maxSize: 10Gi
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
    quotas:
      maxSize: 1.01Ti
  preservePoolsOnDelete: false
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 3
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
