---
connect:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: connect.tu.lsst.org
        paths:
          - /
    pathType: Prefix
    tls:
      - secretName: connect-ingress-tls
        hosts:
          - connect.tu.lsst.org
  serviceType: ClusterIP
