---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: one-pool
  namespace: metallb-system
spec:
  addresses:
  - 139.229.160.201-139.229.160.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - one-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lhn
  namespace: metallb-system
spec:
  addresses:
  - 139.229.180.63-139.229.180.70
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lhn
  namespace: metallb-system
spec:
  ipAddressPools:
  - lhn
  interfaces:
  - br1800
