apiVersion: v1
kind: Service
metadata:
  labels:
    name: htcondor-central-manager
    visualize: "true"
  name: htcondor-central-manager
  namespace: htcondor
spec:
  ports:
    - port: 9618
  selector:
    app: htcondor-central-manager
