---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htcondor-schedd
  namespace: htcondor
  labels:
    app: htcondor-schedd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htcondor-schedd
  template:
    metadata:
      labels:
        app: htcondor-schedd
    spec:
      containers:
      - name: htcondor-schedd
        image: docker.io/lsstit/htcondor-schedd:23
        resources:
          requests:
            memory: "1.0Gi"
            cpu: "1000m"
          limits:
            memory: "1.0Gi"
            cpu: "1000m"
        env:
        - name: CONDOR_HOST
          value: "htcondor-central-manager"
        - name: SEC_PASSWORD_FILE
          value: "/etc/condor/pool_password/password"
        volumeMounts:
        - name: pool-password
          mountPath: /etc/condor/pool_password
        ports:
        - containerPort: 9618
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/htcondor-schedd-liveness
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
