---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "p2p1.2301",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "139.229.145.0/24",
        "rangeStart": "139.229.145.100",
        "rangeEnd": "139.229.145.149",
        "gateway": "139.229.145.254"
      }
    }'
