---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dds
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "enp1s0f1.1201",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp",
        "request": [
          {
            "option": "121"
          }
        ]
      }
    }'
