---
apiVersion: v1
kind: Pod
metadata:
  name: multus-demo
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/macvlan-conf
  labels:
    app: multus-demo
spec:
  initContainers:
    - name: ddsnet4u
      image: lsstit/ddsnet4u:latest
      securityContext:
        privileged: true
  containers:
    - name: iperf
      command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: jhoblitt/iperf
