---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: it
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    quotas:
      maxSize: 10Gi
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 3
      codingChunks: 2
    quotas:
      maxSize: 100Ti
  preservePoolsOnDelete: false
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 3
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
