---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-lhn-demo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lhn
  name: nginx-service-lhn
  namespace: metallb-lhn-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-web-svc
  selector:
    app.kubernetes.io/name: proxy
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: one-pool
  name: nginx-service-one-pool
  namespace: metallb-lhn-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-web-svc
  selector:
    app.kubernetes.io/name: proxy
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: proxy
  name: nginx
  namespace: metallb-lhn-demo
spec:
  containers:
  - image: nginx:stable
    name: nginx
    ports:
    - containerPort: 80
      name: http-web-svc
      protocol: TCP
