---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    o11y.eu/exporter: "puppetdb"
  name: puppetdb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: puppetdb-exporter
      app.kubernetes.io/name: puppetdb-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: puppetdb-exporter
        app.kubernetes.io/name: puppetdb-exporter
    spec:
      containers:
      - image: camptocamp/prometheus-puppetdb-exporter
        imagePullPolicy: IfNotPresent
        name: puppetdb-exporter
        args:
        - "--puppetdb-url=http://puppetdb.dev.lsst.org:8080/pdb/query"
        ports:
        - containerPort: 9635
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9635
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 99
        runAsUser: 99
      serviceAccount: puppetdb-exporter
      serviceAccountName: puppetdb-exporter
      terminationGracePeriodSeconds: 30
---
# Source: puppetdb-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: puppetdb-exporter
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: puppetdb-exporter
    app.kubernetes.io/instance: puppetdb-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9635
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: puppetdb-exporter
    app.kubernetes.io/instance: puppetdb-exporter
---
# Source: puppetdb-exporter/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: puppetdb-exporter
  labels:
    app.kubernetes.io/name: puppetdb-exporter
    app.kubernetes.io/instance: puppetdb-exporter
    o11y.eu/monitor: enabled
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: puppetdb-exporter
      app.kubernetes.io/instance: puppetdb-exporter
  endpoints:
  - port: metrics
    path: /metrics
    honorLabels: false
    scrapeTimeout: 10s
    interval: 15s
---
# Source: puppetdb-exporter/templates/poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: puppetdb-exporter
  labels:
    app.kubernetes.io/name: puppetdb-exporter
    app.kubernetes.io/instance: puppetdb-exporter
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: puppetdb-exporter
      app.kubernetes.io/instance: puppetdb-exporter
---
# Source: puppetdb-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: puppetdb-exporter
  labels:
    app.kubernetes.io/name: puppetdb-exporter
    app.kubernetes.io/instance: puppetdb-exporter
