---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "p2p1.2301",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "139.229.144.128/25",
        "rangeStart": "139.229.144.200",
        "rangeEnd": "139.229.144.250",
        "routes": [
          { "dst": "139.229.167.0/24" },
          { "dst": "139.229.170.0/24" },
          { "dst": "139.229.178.0/24" }
        ],
        "gateway": "139.229.147.254"
      }
    }'
