---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: one-pool
  namespace: metallb-system
spec:
  addresses:
  - 140.252.146.46-140.252.146.59
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - one-pool
  interfaces:
  - bond0
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: general
  namespace: metallb-system
spec:
  addresses:
  - 140.252.147.196-140.252.147.222  # ~140.252.147.192/27
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: general
  namespace: metallb-system
spec:
  ipAddressPools:
  - general
  interfaces:
  - br3035
