---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: one-pool
  namespace: metallb-system
spec:
  addresses:
  - 139.229.151.221-139.229.151.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - one-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lhn
  namespace: metallb-system
spec:
  addresses:
  - 139.229.153.129-139.229.153.158  # ~139.229.153.128/27 (~30host)
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lhn
  namespace: metallb-system
spec:
  ipAddressPools:
  - lhn
  interfaces:
  - br2505
