---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: lfa
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
    quotas:
      maxSize: 10Gi
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 3
      codingChunks: 2
    quotas:
      maxSize: 1Ti
  preservePoolsOnDelete: false
  gateway:
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 3
  healthCheck:
    bucket:
      disabled: false
      interval: 60s
  ldap:
    uri: ldap://ipa1.ls.lsst.org
    binddn: uid=svc_rancher,cn=users,cn=accounts,dc=lsst,dc=cloud
    searchdn: dc=lsst,dc=cloud
    dnattr: uid
    credentialsecret: lfa-ldap
