---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: project
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPools:
    - failureDomain: host
      replicated:
        size: 3
  metadataServer:
    activeCount: 3
    activeStandby: true
  preserveFilesystemOnDelete: false
---
apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: project
  namespace: rook-ceph
spec:
  rados:
    pool: project-data0
    # RADOS namespace where NFS client recovery data is stored in the pool.
    namespace: nfs-ns
  server:
    active: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-ceph-nfs
    ceph_daemon_id: a
    ceph_daemon_type: nfs
    ceph_nfs: project
    instance: a
    nfs: a
    rook_cluster: rook-ceph
  name: rook-ceph-nfs-project
  namespace: rook-ceph
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
  selector:
    app: rook-ceph-nfs
    ceph_daemon_id: a
    ceph_daemon_type: nfs
    ceph_nfs: project
    instance: a
    nfs: a
    rook_cluster: rook-ceph
  type: LoadBalancer
