---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    email: rubinobs-it-las@lsst.org
    solvers:
      - selector:
          dnsZones:
            - ls.lsst.org
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: ZPIEHXTK3ZPMR
            accessKeyIDSecretRef:
              name: route53
              key: AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: route53
              key: AWS_SECRET_ACCESS_KEY
