---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: https://connect.cp.lsst.org
      vaults:
        "k8s cp": 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets
