---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htcondor-pool-password
  namespace: htcondor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: htcondor-pool-password-manke
        property: password
