---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htcondor-worker
  namespace: htcondor
  labels:
    app: htcondor-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: htcondor-worker
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: kube-system/htcondor
      labels:
        app: htcondor-worker
    spec:
      containers:
      - name: htcondor-worker
        image: docker.io/lsstit/htcondor-worker:23
        imagePullPolicy: ifNotPresent
        env:
        - name: CONDOR_HOST
          value: 139.229.152.211
        - name: SEC_PASSWORD_FILE
          value: /etc/condor/pool_password/password
        volumeMounts:
        - name: pool-password
          mountPath: /etc/condor/pool_password
        - name: rsphome
          mountPath: /mnt/rsphome
        - name: project
          mountPath: /mnt/project
        ports:
        - containerPort: 9618
          protocol: TCP
      volumes:
      - name: pool-password
        secret:
          defaultMode: 0600
          secretName: htcondor-pool-password
      - name: rsphome
        nfs:
          path: /rsphome
          server: nfs-rsphome.ls.lsst.org
      - name: project
        nfs:
          path: /project
          server: nfs-project.ls.lsst.org
