---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: htcondor
    metallb.universe.tf/loadBalancerIPs: 139.229.152.211
  labels:
    name: htcondor-central-manager
    visualize: "true"
  name: htcondor-central-manager
  namespace: htcondor
spec:
  ports:
    - port: 9618
  selector:
    app: htcondor-central-manager
  type: LoadBalancer
