---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-backup-scheduled
  namespace: cloudnativepg
spec:
  schedule: "0 0 12,21 * * *" #12:00 UTC (9AM CLT) - 21:00 UTC (6PM CLT) (after nightwork and daywork at the summit)
  backupOwnerReference: self
  cluster:
    name: cnpg-cluster
