---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-cluster-app
  namespace: cloudnativepg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: cnpg-cluster-app-ruka
        property: username
    - secretKey: password
      remoteRef:
        key: cnpg-cluster-app-ruka
        property: password
