---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-cnpg-rw
  namespace: cloudnativepg
spec:
  cluster:
    name: cnpg-cluster

  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "500"
      default_pool_size: "100"
---
apiVersion: v1
kind: Service
metadata:
  name: pooler-cnpg-loadbalancer
  namespace: cloudnativepg
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: pooler-cnpg-rw
