---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lfa
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: my-store
  objectStoreNamespace: rook-ceph
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: lfa-cp-dev
  namespace: rook-ceph
spec:
  generateBucketName: lfa-cp-dev
  storageClassName: lfa
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: lfa-cp-dev
  namespace: rook-ceph
spec:
  store: my-store
  displayName: "CP LFA User"
