---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: one-pool
  namespace: metallb-system
spec:
  addresses:
  - 139.229.151.150-139.229.151.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - one-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lhn
  namespace: metallb-system
spec:
  addresses:
  - 139.229.153.65-139.229.153.126  # ~139.229.153.64/26
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lhn
  namespace: metallb-system
spec:
  ipAddressPools:
  - lhn
  interfaces:
  - br2505
