---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: lhn
  labels:
    cnpg.io/cluster: cnpg-cluster
  name: cnpg-loadbalancer-lhn
  namespace: cloudnativepg
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgresql: cnpg-cluster
    role: primary
  sessionAffinity: None
  type: LoadBalancer
