---
apiVersion: v1
kind: Namespace
metadata:
  name: svclhntest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: svclhntest
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: ruka01
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: svclhntest
  annotations:
    metallb.universe.tf/address-pool: lhn
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: LoadBalancer
