---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: one-pool
  namespace: metallb-system
spec:
  addresses:
  - 139.229.135.140-139.229.135.149
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2ad
  namespace: metallb-system
spec:
  ipAddressPools:
  - one-pool
